runtime: nodejs

env: flex

env_variables:
  NODE_ENV: "production"

beta_settings:
  cloud_sql_instances: "wildepoint-backend-349002:europe-west2:wildepoint-strapi"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

resources:
  cpu: 1
  memory_gb: 3.75
  disk_size_gb: 10
